official-repo: &official-repo
  DanySK/Template-Elsevier-Article

language: java

addons:
  apt:
    update: true
    packages:
      # LaTeX decent font processor
      - cm-super
      # For Minted
      - python-pygments
      # LaTeX
      - texlive-base
      - texlive-extra-utils
      - texlive-generic-recommended
      - texlive-latex-extra
      - texlive-latex-recommended
      - texlive-fonts-recommended
      - texlive-science
      - texlive-publishers
      # Debug
      - tree
      # For git latexdiff
      - latexdiff
      # Image processing
      - inkscape

env:
  global:
    - TERM=dumb
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"

install: true

script:
  - latex elsarticle.ins
  - ./gradlew buildLatex    

before_deploy:
  - git config --local user.name "Danilo Pianini"
  - git config --local user.email "danilo.pianini@unibo.it"
  - if [[ $(git describe) == *"-"* ]]; then git tag $(git describe) || :; fi

before_cache:
  - curl "${GRAVIS}.clean_gradle_cache.sh" --output .clean_gradle_cache.sh
  - bash .clean_gradle_cache.sh

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  - provider: releases
    api_key:
      secure: "JL1/19H0fbYACTmqIUL89BFFD3a6jGS6c169zf1DpqBDM8VTAPL1eExyDv7sH35UBL3uvb6lNV21VIKG/R9ePCqqnJL63YLi1lvar+PFC2dS4faHBiC5lti/+xlTJhB1Jmu2XfpQSyzwO/+wzQQZUhDSM7ZUfe222c5PsoSSwy+65aE/pxYvUMXhSDDNjpd/PbZEmUzmCbxNZh9jwfCOTdQskF7m/Y/aCw883YLQ/nNzhYS0LxdJPl2UbjS0wTizOYVLEW2bhHdXjS27n9V1/rprmGgOti2J+Rakm+tNh62ZdZYgCOLm64lnDKX4HmgSPoHFOpNX1mHl0AA+nDrBQlbZDzosa57n98h/A6I6g+RL02q1e2zMMwC3hIwUK8rj/EgT+bTbfKmWGHQLahaJkw6LYQVB0NVsfi6EsCmSCQS7KZr+Y4mAdflOuneb98lNtf8/0lRFBMoFm6v0PYq8wHVJExMPzLu2BqC7eYeDqBodkxBiuAgE83IdMdumZnyb5jHdRrkh/EcGfIIoGGXz18PwHiQHNO4slSuEYurUwDWuSocj1JFTS+/dkrdNhgdUNUIAcNcg7t+NJnykwmkd0gzdQm2LBp61U7IA4cBKmWKp6eniRJG8qYZTs3Zv33OOS6xny/BiLYusWlN95PKmx9h3sJg2hmKBUKTKRTnzRek="
    file_glob: true
    file: "*.pdf"
    skip_cleanup: true
    on:
      repo: *official-repo
      tags: true
  - provider: releases
    api_key:
      secure: "JL1/19H0fbYACTmqIUL89BFFD3a6jGS6c169zf1DpqBDM8VTAPL1eExyDv7sH35UBL3uvb6lNV21VIKG/R9ePCqqnJL63YLi1lvar+PFC2dS4faHBiC5lti/+xlTJhB1Jmu2XfpQSyzwO/+wzQQZUhDSM7ZUfe222c5PsoSSwy+65aE/pxYvUMXhSDDNjpd/PbZEmUzmCbxNZh9jwfCOTdQskF7m/Y/aCw883YLQ/nNzhYS0LxdJPl2UbjS0wTizOYVLEW2bhHdXjS27n9V1/rprmGgOti2J+Rakm+tNh62ZdZYgCOLm64lnDKX4HmgSPoHFOpNX1mHl0AA+nDrBQlbZDzosa57n98h/A6I6g+RL02q1e2zMMwC3hIwUK8rj/EgT+bTbfKmWGHQLahaJkw6LYQVB0NVsfi6EsCmSCQS7KZr+Y4mAdflOuneb98lNtf8/0lRFBMoFm6v0PYq8wHVJExMPzLu2BqC7eYeDqBodkxBiuAgE83IdMdumZnyb5jHdRrkh/EcGfIIoGGXz18PwHiQHNO4slSuEYurUwDWuSocj1JFTS+/dkrdNhgdUNUIAcNcg7t+NJnykwmkd0gzdQm2LBp61U7IA4cBKmWKp6eniRJG8qYZTs3Zv33OOS6xny/BiLYusWlN95PKmx9h3sJg2hmKBUKTKRTnzRek="
    file_glob: true
    file: "*.pdf"
    skip_cleanup: true
    on:
      repo: *official-repo
      tags: false

notifications:
  email:
    on_success: never
